services:
  messaging_app:
    build:
      context: .
      dockerfile: ./docker/laravel/Dockerfile
    container_name: messaging_app
    working_dir: /var/www
    expose:
      - 9000
    volumes:
      - ./:/var/www
    user: "1000:1000"
    networks:
      - messaging_app
    depends_on:
      - mysql
    env_file:
      - .env
    profiles:
      - dev

  frontend:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: messaging_frontend
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
    depends_on:
      - messaging_app
    networks:
      - messaging_app
    profiles:
      - dev

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - messaging_app
      - frontend
    networks:
      - messaging_app
    profiles:
      - dev

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: messaging_app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - messaging_app
    profiles:
      - dev
      
  migrations:
    build:
      context: .
      dockerfile: ./docker/laravel/Dockerfile
    command: php artisan migrate --seed
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - messaging_app
    networks:
      - messaging_app
    restart: "no"
    env_file:
      - .env
  scheduler:
    build:
      context: .
      dockerfile: ./docker/laravel/Dockerfile
    container_name: scheduler
    volumes:
      - .:/var/www
    depends_on:
      - messaging_app
    command: php artisan schedule:work
    networks:
      - messaging_app
    env_file:
      - .env
    profiles:
      - dev

  queue:
    build:
      context: .
      dockerfile: ./docker/laravel/Dockerfile
    container_name: queue
    volumes:
      - .:/var/www
    command: php artisan queue:work
    networks:
      - messaging_app
    env_file:
      - .env

volumes:
  database_data:

networks:
  messaging_app:
    driver: bridge